################################################################################
# 
# Jekyll Configuration
# 
# http://jekyllrb-ja.github.io/docs/configuration/default/
#
################################################################################

# Basic Info
title: Rem_Note
description: 自分がしたことや考えたことなどを備忘録として記録する場所

# Author
author:
  name: Rem_
  email: ""
  copyright: 2021 Rem_
  github: "silverag-corgi"
  twitter: "silverag_corgi"

################################################################################

# Handling Reading
safe: false
exclude: 
  - README.md
  - LICENSE

# Serving
# url is hostname of site.
# baseurl is subpath of site and repository name.
url: "https://silverag-corgi.github.io"
baseurl: "/blog"

# Outputting
permalink: "/posts/:categories/:title/"

# Plugins
plugins:
  - jekyll-paginate-v2

# Conversion
markdown: kramdown
kramdown:
  parse_block_html: true
highlighter: rouge
excerpt_separator: "<!-- more -->"

# Plugins Configuration

## Pagination
## https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true
  sort_field: "date"
  title: ":title - :num/:max"
  trail:
    before: 3
    after: 3

## Auto Generating Pages
## https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md
autopages:
  enabled: true
  tags:
    enabled: true
    layouts:
      - "autopage-tag.html"
    title: "タグ - :tag"
    permalink: "/tags/:tag"
    silent: false
    slugify:
      mode: "default"
      case: false
  categories: 
    enabled: true
    layouts:
      - "autopage-category.html"
    title: "カテゴリ - :cat"
    permalink: "/posts/:cat"
    silent: false
    slugify:
      mode: "default"
      case: false
  collections:
    enabled: false

## Access Analytics Service
google_analytics_key: 

################################################################################

# Original Configuration

## Favicon
favicon: "/assets/img/favicon01.ico"

## RSS
rss: "/feed.xml"

## Share Buttons
share:
  twitter: true
  line: true

## Recent Posts
recent_posts: 5

## Content Excerpt Characters
excerpt_chars: 130

## Change Log URL
change_log_url: "https://github.com/silverag-corgi/blog/commits/master/"

