# Jekyll configuration

# Site Name And Description
name: Rem_ Lab
description: >-
  <p>備忘録や関心事のメモを保存する場所。</p>
  <p>個人的な使用がメインなので細々とやっていきます。</p>

# The Base Hostname of Site
url: 'https://silverag-corgi.github.io'

# The Subpath of Site, Repository Name, Project Name
baseurl: ''

# Timezone
#timezone: Asia/Tokyo

author: Rem_
copyright: 2021

# Share Buttons
share:
  twitter: true
#  facebook: true
#  gplus: true
#  linkedin: true
#  pinterest: true
#  email: true

# My SNS Accounts
social:
  github: silverag-corgi
  twitter: silverag_corgi
#  stackoverflow: ''
#  linkedin: ''
#  instagram: ''
#  lastfm: ''
#  rss: feed.xml

# Access Analytics Service
google_analytics_key: 
yandex_metrica: 

# Comment System
disqus: 
comments: false

# URL of Post
permalink: '/post/:year:month:day/:title/'

# Pagination
paginate: 5
paginate_path: '/pages/:num/'

# Recent Posts
recent_posts: 5

# Popular Tags
popular_tags: 5

# Markdown Rendering Engine
markdown: kramdown
kramdown:
  input: GFM       # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false # New Line

# Plugins
plugins:
  - jekyll-paginate

# Excluded File
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - jekyll-clean-dark.gemspec
  - LICENSE
