################################################################################
# 
# Jekyll Configuration
# 
# http://jekyllrb-ja.github.io/docs/configuration/default/
#
################################################################################

# Basic Info
title: Rem_Note
description: >-
  自分がしたことや考えたことなどを備忘録として記録する場所

# Author
author:
  name: Rem_
  email: ""
  copyright: 2021 Rem_
  github: "silverag-corgi"
  twitter: "silverag_corgi"

################################################################################

# Handling Reading
safe: false
exclude: 
  - README.md
  - JekyllCleanDarkTheme.md
  - LICENSE

# Serving
# url is hostname of site.
# baseurl is subpath of site and repository name.
url: "https://silverag-corgi.github.io"
baseurl: ""

# Outputting
permalink: "/post/:year:month:day/:title/"

# Plugins
plugins:
  - jekyll-paginate-v2

# Plugins Configuration

## Paginate
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true
  sort_field: "date"
  title: ":title - :num/:max"
  trail:
    before: 3
    after: 3

## Content Excerpt Separator
excerpt_separator: "<!-- more -->"

## Access Analytics Service
google_analytics_key: 

################################################################################

# Original Configuration

## Favicon
favicon: "/assets/img/favicon01.ico"

## RSS
rss: "/contents/feed.xml"

## Share Buttons
share:
  twitter: true
  facebook: false

## Recent Posts
recent_posts: 5

## Content Excerpt Characters
excerpt_chars: 130

## Change Log URL
change_log_url: "https://github.com/silverag-corgi/silverag-corgi.github.io/commits/master/"

